var gridDatas = [
  　　{
    　　　　"CityID":"4",
    　　　　"CityName":"北京"
    　　},
  　　{
    　　　　"CityID":"7",
    　　　　"CityName":"上海"
    　　},
  　　{
    　　　　"CityID":"10",
    　　　　"CityName":"广州"
    　　},
  　　{
    　　　　"CityID":"13",
    　　　　"CityName":"深圳"
    　　},
  　　{
    　　　　"CityID":"16",
    　　　　"CityName":"成都"
    　　},
  　　{
    　　　　"CityID":"19",
    　　　　"CityName":"武汉"
    　　},
  　　{
    　　　　"CityID":"22",
    　　　　"CityName":"杭州"
    　　},
  　　{
    　　　　"CityID":"25",
    　　　　"CityName":"南京"
    　　},
  　　{
    　　　　"CityID":"28",
    　　　　"CityName":"天津"
    　　},
  　　{
    　　　　"CityID":"31",
    　　　　"CityName":"西安"
    　　},
  　　{
    　　　　"CityID":"34",
    　　　　"CityName":"重庆"
    　　},
  　　{
    　　　　"CityID":"37",
    　　　　"CityName":"青岛"
    　　},
  　　{
    　　　　"CityID":"40",
    　　　　"CityName":"沈阳"
    　　},
  　　{
    　　　　"CityID":"43",
    　　　　"CityName":"长沙"
    　　},
  　　{
    　　　　"CityID":"46",
    　　　　"CityName":"大连"
    　　},
  　　{
    　　　　"CityID":"49",
    　　　　"CityName":"厦门"
    　　},
  　　{
    　　　　"CityID":"52",
    　　　　"CityName":"无锡"
    　　},
  　　{
    　　　　"CityID":"55",
    　　　　"CityName":"福州"
    　　},
  　　{
    　　　　"CityID":"58",
    　　　　"CityName":"济南"
    　　},
  　　{
    　　　　"CityID":"61",
    　　　　"CityName":"昆明"
    　　},
  　　{
    　　　　"CityID":"64",
    　　　　"CityName":"郑州"
    　　},
  　　{
    　　　　"CityID":"67",
    　　　　"CityName":"长春"
    　　},
  　　{
    　　　　"CityID":"70",
    　　　　"CityName":"南昌"
    　　},
  　　{
    　　　　"CityID":"73",
    　　　　"CityName":"三亚"
    　　},
  　　{
    　　　　"CityID":"76",
    　　　　"CityName":"揭阳"
    　　},
  　　{
    　　　　"CityID":"79",
    　　　　"CityName":"哈尔滨"
    　　},
  　　{
    　　　　"CityID":"82",
    　　　　"CityName":"石家庄"
    　　},
  　　{
    　　　　"CityID":"85",
    　　　　"CityName":"香港"
    　　}
]
