const clist = [
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-1",
		"ChannelNumber": "1",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.1:1030",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-2",
		"ChannelNumber": "2",
		"Frequency": "3",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.2:1031",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-3",
		"ChannelNumber": "3",
		"Frequency": "5",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.158:1194",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-4",
		"ChannelNumber": "4",
		"Frequency": "6",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.4:1033",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-5",
		"ChannelNumber": "5",
		"Frequency": "7",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.159:1195",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-6",
		"ChannelNumber": "6",
		"Frequency": "9",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.160:1196",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-7",
		"ChannelNumber": "7",
		"Frequency": "10",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.7:1036",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	}
]
