const clist = [
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-1",
		"ChannelNumber": "1",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.1:1030",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-2",
		"ChannelNumber": "2",
		"Frequency": "3",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.2:1031",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-3",
		"ChannelNumber": "3",
		"Frequency": "5",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.158:1194",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-4",
		"ChannelNumber": "4",
		"Frequency": "6",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.4:1033",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-5",
		"ChannelNumber": "5",
		"Frequency": "7",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.159:1195",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-6",
		"ChannelNumber": "6",
		"Frequency": "9",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.160:1196",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-7",
		"ChannelNumber": "7",
		"Frequency": "10",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.7:1036",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-8",
		"ChannelNumber": "8",
		"Frequency": "12",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.161:1197",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-9",
		"ChannelNumber": "9",
		"Frequency": "13",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.9:1038",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-10",
		"ChannelNumber": "10",
		"Frequency": "15",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.10:1039",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-11",
		"ChannelNumber": "11",
		"Frequency": "17",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.11:1040",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-12",
		"ChannelNumber": "12",
		"Frequency": "18",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.12:1041",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-13",
		"ChannelNumber": "13",
		"Frequency": "20",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.13:1042",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-14",
		"ChannelNumber": "14",
		"Frequency": "21",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.14:1043",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-15",
		"ChannelNumber": "15",
		"Frequency": "23",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.15:1044",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CGTN",
		"ChannelNumber": "16",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.16:1045",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南卫视",
		"ChannelNumber": "17",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.51:1080",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南都市频道",
		"ChannelNumber": "18",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.52:1081",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南民生频道",
		"ChannelNumber": "19",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.53:1082",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南法治频道",
		"ChannelNumber": "20",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.54:1083",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南电视剧",
		"ChannelNumber": "21",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.55:1084",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南新闻频道",
		"ChannelNumber": "22",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.56:1085",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南欢腾购物",
		"ChannelNumber": "23",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.57:1086",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南公共频道",
		"ChannelNumber": "24",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.58:1087",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南新农村",
		"ChannelNumber": "25",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.120:1149",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南国际频道",
		"ChannelNumber": "26",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.102:1131",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "睛彩中原",
		"ChannelNumber": "27",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.163:1203",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "移动戏曲",
		"ChannelNumber": "28",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.161:1203",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南文物宝库",
		"ChannelNumber": "29",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.100:1129",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南梨园频道",
		"ChannelNumber": "30",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.99:1128",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南武术世界",
		"ChannelNumber": "31",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.101:1130",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "湖南卫视",
		"ChannelNumber": "32",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.17:1046",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "江苏卫视",
		"ChannelNumber": "33",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.18:1047",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "浙江卫视",
		"ChannelNumber": "34",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.19:1048",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "北京卫视",
		"ChannelNumber": "35",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.21:1050",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "东方卫视",
		"ChannelNumber": "36",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.22:1051",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "天津卫视",
		"ChannelNumber": "37",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.24:1053",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "山东卫视",
		"ChannelNumber": "38",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.27:1056",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "安徽卫视",
		"ChannelNumber": "39",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.20:1049",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "深圳卫视",
		"ChannelNumber": "40",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.23:1052",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "江西卫视",
		"ChannelNumber": "41",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.37:1066",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "湖北卫视",
		"ChannelNumber": "42",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.35:1064",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "四川卫视",
		"ChannelNumber": "43",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.40:1069",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "黑龙江卫视",
		"ChannelNumber": "44",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.28:1057",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "云南卫视",
		"ChannelNumber": "45",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.33:1062",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "贵州卫视",
		"ChannelNumber": "46",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.41:1070",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "辽宁卫视",
		"ChannelNumber": "47",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.26:1055",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "东南卫视",
		"ChannelNumber": "48",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.32:1061",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "重庆卫视",
		"ChannelNumber": "49",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.29:1058",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "广东卫视",
		"ChannelNumber": "50",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.30:1059",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "广西卫视",
		"ChannelNumber": "51",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.31:1060",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河北卫视",
		"ChannelNumber": "52",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.34:1063",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "旅游卫视",
		"ChannelNumber": "53",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.25:1054",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "吉林卫视",
		"ChannelNumber": "54",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.36:1065",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "山西卫视",
		"ChannelNumber": "55",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.38:1067",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "陕西卫视",
		"ChannelNumber": "56",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.39:1068",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "甘肃卫视",
		"ChannelNumber": "57",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.42:1071",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "宁夏卫视",
		"ChannelNumber": "58",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.43:1072",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "青海卫视",
		"ChannelNumber": "59",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.44:1073",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "内蒙古卫视",
		"ChannelNumber": "60",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.45:1074",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "西藏卫视",
		"ChannelNumber": "61",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.46:1075",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "新疆卫视",
		"ChannelNumber": "62",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.47:1076",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "卡酷动画",
		"ChannelNumber": "63",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.48:1077",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "金鹰卡通",
		"ChannelNumber": "64",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.49:1078",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "嘉佳卡通",
		"ChannelNumber": "65",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.92:1121",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "中国教育-1高清",
		"ChannelNumber": "66",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.173:1712",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "中国教育-4",
		"ChannelNumber": "67",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.171:1710",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "厦门卫视",
		"ChannelNumber": "68",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.95:1124",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "金鹰纪实高清",
		"ChannelNumber": "69",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.172:1711",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "兵团卫视",
		"ChannelNumber": "70",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.97:1126",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CETV2",
		"ChannelNumber": "71",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.165:1206",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "山东教育",
		"ChannelNumber": "72",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.164:1205",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "音乐现场",
		"ChannelNumber": "73",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.184:1224",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "熊猫频道",
		"ChannelNumber": "74",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.169:1221",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "爱生活",
		"ChannelNumber": "75",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.176:1225",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "好学生",
		"ChannelNumber": "76",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.177:1226",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "国学",
		"ChannelNumber": "77",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.178:1227",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "早教",
		"ChannelNumber": "78",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.179:1228",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "高网",
		"ChannelNumber": "79",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.180:1229",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "军事",
		"ChannelNumber": "80",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.181:1230",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "美妆",
		"ChannelNumber": "81",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.182:1231",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "地理",
		"ChannelNumber": "82",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.183:1232",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "经典电影",
		"ChannelNumber": "83",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.175:1233",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV谍战剧场",
		"ChannelNumber": "84",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.185:1240",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV相声小品",
		"ChannelNumber": "85",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.186:1235",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV野外",
		"ChannelNumber": "86",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.187:1236",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV法治",
		"ChannelNumber": "87",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.188:1237",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "少儿动画",
		"ChannelNumber": "88",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.189:1238",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "热播剧场",
		"ChannelNumber": "89",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.190:1239",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "魅力时尚",
		"ChannelNumber": "90",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.159:1201",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV3＋",
		"ChannelNumber": "91",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.160:1202",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV5＋",
		"ChannelNumber": "92",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.5:1034",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV6＋",
		"ChannelNumber": "93",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.6:1035",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV8＋",
		"ChannelNumber": "94",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "mp://225.1.4.8:1037",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "收视指南",
		"ChannelNumber": "95",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.50:1079",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-1高清",
		"ChannelNumber": "96",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.73:1102",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-2高清",
		"ChannelNumber": "97",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.74:1103",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-5＋高清",
		"ChannelNumber": "98",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.75:1104",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-7高清",
		"ChannelNumber": "99",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.76:1105",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-9高清",
		"ChannelNumber": "100",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.77:1106",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-10高清",
		"ChannelNumber": "101",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.78:1107",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-12高清",
		"ChannelNumber": "102",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.79:1108",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "CCTV-14高清",
		"ChannelNumber": "103",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.80:1109",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "河南卫视高清",
		"ChannelNumber": "104",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.98:1127",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "浙江卫视高清",
		"ChannelNumber": "105",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.84:1113",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "东方卫视高清",
		"ChannelNumber": "106",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.85:1114",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "天津卫视高清",
		"ChannelNumber": "107",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.86:1115",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "安徽卫视高清",
		"ChannelNumber": "108",
		"Frequency": "0",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.87:1116",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "山东卫视高清",
		"ChannelNumber": "109",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.88:1117",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "湖北卫视高清",
		"ChannelNumber": "110",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.89:1118",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "深圳卫视高清",
		"ChannelNumber": "111",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.90:1119",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "黑龙江高清",
		"ChannelNumber": "112",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.91:1120",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "北京卫视高清",
		"ChannelNumber": "113",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.81:1110",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "湖南卫视高清",
		"ChannelNumber": "114",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.82:1111",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "江苏卫视高清",
		"ChannelNumber": "115",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.83:1112",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "广东卫视高清",
		"ChannelNumber": "116",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.166:1207",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "辽宁卫视高清",
		"ChannelNumber": "117",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.167:1208",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "IPTV5＋高清",
		"ChannelNumber": "118",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.168:1220",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "高清纪实",
		"ChannelNumber": "119",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.170:1222",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州时政频道",
		"ChannelNumber": "120",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.143:1179 igmp://225.1.4.145:1181",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州商都频道",
		"ChannelNumber": "121",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.144:1180",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州文体频道",
		"ChannelNumber": "122",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.145:1181",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州影视戏曲",
		"ChannelNumber": "123",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.145:1181",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州影视戏曲",
		"ChannelNumber": "124",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.146:1182",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州妇女儿童",
		"ChannelNumber": "125",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.147:1183",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "精彩郑州",
		"ChannelNumber": "126",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.148:1184",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州时政高清",
		"ChannelNumber": "127",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.140:1176",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州商都高清",
		"ChannelNumber": "128",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.141:1177",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	},
	{
		"AudioFormat": "0",
		"AudioPid": "0",
		"ChannelName": "郑州文体高清",
		"ChannelNumber": "129",
		"Frequency": "1",
		"Language": "chi",
		"LiveUrl": "igmp://225.1.4.142:1178",
		"LogoSize": 0,
		"LogoUrl": "",
		"ModulationMode": "PAL_DK",
		"PcrPid": "0",
		"QamSize": "0",
		"ServiceID": 0,
		"SymbolRate": "0",
		"Type": 3,
		"VideoFormat": "0",
		"VideoPid": "0"
	}
]
